initial installing commands

In [1]:
# !pip install "alphatims[plotting]"

# !pip install hvplot

# !pip install jupyter_bokeh

# !pip install dask[dataframe]

# !pip install matplotlib

# !pip install scikit-learn

# pip install mplcursors

# pip install mpld3

In [2]:
import alphatims.utils
import alphatims.bruker
import alphatims.plotting
import importlib


alphatims.utils.set_threads(4)
log_file_name = alphatims.utils.set_logger(
    log_file_name="tutorial_log.txt",
    overwrite=True
)

def reload():
    importlib.reload(alphatims.utils)
    importlib.reload(alphatims.bruker)
    importlib.reload(alphatims.plotting)
    alphatims.utils.set_threads(4)
    alphatims.utils.set_logger(log_file_name="tutorial_log.txt")
    
isDia = True

if (isDia):
    # bruker_d_folder_name = "../MS_Data/P4139_02_1_1_509.hdf"
    # bruker_d_folder_name = "../MS_Data/20201207_tims03_Evo03_PS_SA_HeLa_200ng_EvoSep_prot_high_speed_21min_8cm_S1-C8_1_22474.hdf"
    bruker_d_folder_name = "../MS_Data/test1.hdf"
    
else :
    bruker_d_folder_name = ""

data = alphatims.bruker.TimsTOF(bruker_d_folder_name)

2025-03-07 08:23:59> Importing data from ../MS_Data/test1.hdf
2025-03-07 08:23:59> Using HDF import for ../MS_Data/test1.hdf
2025-03-07 08:24:09> Successfully imported data from ../MS_Data/test1.hdf

_Convert raw file (.d) to HDF5_

In [3]:

# hdf_file_name = data.save_as_hdf(
#     directory=data.directory,
#     file_name=f"{data.sample_name}.hdf",
#     overwrite=True
# )

In [5]:
# auxilary functions

dir(data)
alphatims.utils.show_platform_info()
data.tof_indices.max()
data.meta_data

2025-03-07 08:24:24> Platform information:
2025-03-07 08:24:24> system        - Windows
2025-03-07 08:24:24> release       - 11
2025-03-07 08:24:24> version       - 10.0.26100
2025-03-07 08:24:24> machine       - AMD64
2025-03-07 08:24:24> processor     - Intel64 Family 6 Model 140 Stepping 1, GenuineIntel
2025-03-07 08:24:24> cpu count     - 8
2025-03-07 08:24:24> cpu frequency - 2803.00 Mhz
2025-03-07 08:24:24> ram           - 2.5/15.7 Gb (available/total)
2025-03-07 08:24:24>

{'AcquisitionDateTime': '2021-05-10T10:18:01.467+01:00',
 'AcquisitionFirmwareVersion': 'I4IT-12.20.0.0; ITPT-12.20.0.0; ITET-12.20.0.0; FXM3-0.0.1.6; MXMC-0.0.4.1; MXIF-0.0.1.1; MXI2-NOT_PRESENT; MXRF-0.0.1.1; RFXS-0.1.3.1; RFXE-NOT_PRESENT',
 'AcquisitionSoftware': 'timsTOF',
 'AcquisitionSoftwareVendor': 'Bruker',
 'AcquisitionSoftwareVersion': '2.1.90',
 'AnalysisId': '00000000-0000-0000-0000-000000000000',
 'ClosedProperly': '1',
 'DenoisingEnabled': '0',
 'Description': '',
 'DigitizerNumSamples': '394535',
 'InstrumentFamily': '9',
 'InstrumentName': 'impacTEM-pt',
 'InstrumentRevision': '1',
 'InstrumentSerialNumber': '1854399.00095',
 'InstrumentSourceType': '11',
 'InstrumentVendor': 'Bruker',
 'MaxNumPeaksPerScan': '2003',
 'MethodName': '20210416_diaPASEF_high_speed_IM_06_16.m',
 'MzAcqRangeLower': '100.000000',
 'MzAcqRangeUpper': '1700.000000',
 'OneOverK0AcqRangeLower': '0.600000',
 'OneOverK0AcqRangeUpper': '1.600000',
 'OperatorName': 'Admin',
 'PeakListIndexScaleFactor': '1',
 'PeakWidthEstimateType': '1',
 'PeakWidthEstimateValue': '0.000025',
 'SampleName': '20210510_TIMS03_EVO03_PaSk_SA_HeLa_50ng_5_6min_DIA_high_speed',
 'SchemaType': 'TDF',
 'SchemaVersionMajor': '3',
 'SchemaVersionMinor': '5',
 'TimsCompressionType': '2'}

Selecting the precursor in the fist quardupole window

In [13]:
i = 1

# window_1_precursor = data[:,:,0,:]
window_1_precursor = data[:,:,0,400.0:425.0]
window_1_precursor

,raw_indices,frame_indices,scan_indices,precursor_indices,push_indices,tof_indices,rt_values,rt_values_min,mobility_values,quad_low_mz_values,quad_high_mz_values,mz_values,intensity_values,corrected_intensity_values
0,3725,1,146,0,1074,127662,0.504660,0.008411,1.474541,-1.0,-1.0,404.242763,147,147
1,11663,1,206,0,1134,132644,0.504660,0.008411,1.407173,-1.0,-1.0,420.256525,80,80
2,13062,1,213,0,1141,130823,0.504660,0.008411,1.399315,-1.0,-1.0,414.367173,139,139
3,15065,1,222,0,1150,131141,0.504660,0.008411,1.389213,-1.0,-1.0,415.392632,10,10
4,17837,1,233,0,1161,131668,0.504660,0.008411,1.376867,-1.0,-1.0,417.094846,55,55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2539456,126975343,3176,33,0,2947361,126996,337.172372,5.619540,1.601499,-1.0,-1.0,402.125593,33,33
2539457,126975344,3176,33,0,2947361,127026,337.172372,5.619540,1.601499,-1.0,-1.0,402.220841,138,138
2539458,126975345,3176,33,0,2947361,128881,337.172372,5.619540,1.601499,-1.0,-1.0,408.132281,122,122
2539459,126975346,3176,33,0,2947361,129883,337.172372,5.619540,1.601499,-1.0,-1.0,411.343353,140,140
2539460,126975347,3176,33,0,2947361,133525,337.172372,5.619540,1.601499,-1.0,-1.0,423.120710,158,158

Plotting the Precursors (window 1 precursors) in a head map

In [7]:
import hvplot as hv
calibrant_mz = 1221.990637
ppm_error = 5
calibrant_low_mz = calibrant_mz / (1 + ppm_error / 10**6)
calibrant_high_mz = calibrant_mz * (1 + ppm_error / 10**6)
# df = data[:, :, 0, 400.0 :425.0]
heatmap = alphatims.plotting.heatmap(
    window_1_precursor,
    x_axis_label="mz",
    y_axis_label="mobility",
    title="window_1_precursor",
    width=900
)
hv.save(heatmap, "tutorial_heatmap.html")
heatmap

BokehModel(combine_events=True, render_bundle={'docs_json': {'7cd30f3b-b554-4a78-9411-bf0b6936dc70': {'version…

Selecting the fragment related to the quadrupole window

In [8]:
window_1_fragments= data[:,:,1,:]   #data.__getitem__((slice(None), slice(None), 2, slice(None)))
quad_low_mz_values = window_1_fragments['quad_low_mz_values'].unique()
quad_high_mz_values = window_1_fragments['quad_high_mz_values'].unique()
print(quad_high_mz_values,quad_low_mz_values)

# i= 0
# window_1_precursor = window_1_precursor[(precursor_temp['mz_values']>=quad_low_mz_values[2-i]) & (precursor_temp['mz_values']<quad_high_mz_values[2-i])]
# window_1_precursor

[825. 625. 425.] [800. 600. 400.]

In [14]:
import numpy as np
import pandas as pd


# finding the similar raws with the selected thresholds 
def group_similar_rows(df, rt_tolerance, mobility_tolerance, mz_tolerance):
    min_values = df.min()
    max_values = df.max()
    
    rt_min_value = min_values['rt_values']
    rt_max_value = max_values['rt_values']
    
    mobility_min_value = min_values['mobility_values']
    mobility_max_value = max_values['mobility_values']
    
    mz_min_values = min_values['mz_values']
    mz_max_values = max_values['mz_values']
    
    
    df = df.sort_values(by=["rt_values"]).reset_index(drop=True)
    rt_bins = np.arange(rt_min_value, rt_max_value + rt_tolerance, rt_tolerance)
    df["rt_group"] = pd.cut(df["rt_values"], rt_bins,  labels=rt_bins[:-1])
    
    
    df = df.sort_values(by=["mobility_values"]).reset_index(drop=True)
    mobility_bins = np.arange(mobility_min_value, mobility_max_value + mobility_tolerance, mobility_tolerance)
    df["mobility_group"] = pd.cut(df["mobility_values"], mobility_bins,  labels=mobility_bins[:-1])
    
    
    df = df.sort_values(by=["mz_values"]).reset_index(drop=True)
    mobility_bins = np.arange(mz_min_values, mz_max_values +mz_tolerance, mz_tolerance)
    df["mz_group"] = pd.cut(df["mz_values"], mobility_bins,  labels=mobility_bins[:-1])
    
    

    grouped_df = df.groupby(["rt_group", "mobility_group", "mz_group"], observed=True).agg({
        "rt_values": "mean",
        "mobility_values": "mean",
        "mz_values": "mean",
        "intensity_values": "sum"
    }).reset_index(drop=True)
    
    


    return grouped_df

In [10]:
import numpy as np
import pandas as pd
from sklearn.cluster import DBSCAN
from sklearn.preprocessing import StandardScaler

def group_isotopes_optimized(df, mz_tolerance=0.02, rt_tolerance=0.3, mobility_tolerance=0.01):
    min_values = df.min()
    max_values = df.max()
    
    rt_min_value = min_values['rt_values']
    rt_max_value = max_values['rt_values']
    
    mobility_min_value = min_values['mobility_values']
    mobility_max_value = max_values['mobility_values']
    
    mz_min_values = min_values['mz_values']
    mz_max_values = max_values['mz_values']
    
    
    df = df.sort_values(by=["rt_values"]).reset_index(drop=True)
    rt_bins = np.arange(rt_min_value, rt_max_value + rt_tolerance, rt_tolerance)
    df["rt_group"] = pd.cut(df["rt_values"], rt_bins,  labels=rt_bins[:-1])
    
    
    df = df.sort_values(by=["mobility_values"]).reset_index(drop=True)
    mobility_bins = np.arange(mobility_min_value, mobility_max_value + mobility_tolerance, mobility_tolerance)
    df["mobility_group"] = pd.cut(df["mobility_values"], mobility_bins,  labels=mobility_bins[:-1])
    
    
    df = df.sort_values(by=["mz_values"]).reset_index(drop=True)
    mobility_bins = np.arange(mz_min_values, mz_max_values +mz_tolerance, mz_tolerance)
    df["mz_group"] = pd.cut(df["mz_values"], mobility_bins,  labels=mobility_bins[:-1])
    
    

    # grouped_sets = set(df.groupby(["rt_group", "mobility_group", "mz_group"]).groups.keys())
    df["peptide_group"] = df.groupby(["rt_group", "mobility_group", "mz_group"]).ngroup()


    
    return df
    
    


# Group isotopes (FAST!)
isotope_groups = group_isotopes_optimized(window_1_precursor)

# # Print grouped isotope sets
# for idx, group in enumerate(isotope_groups):
#     print(f"Isotope Group {idx + 1}:")
#     print(group, "\n")

C:\Users\havin\AppData\Local\Temp\ipykernel_23856\3369013978.py:37: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df["peptide_group"] = df.groupby(["rt_group", "mobility_group", "mz_group"]).ngroup()

In [11]:
# for idx, group in enumerate(isotope_groups):
#     print(f"Isotope Group {idx + 1}:")
#     print(group, "\n")
#     break
isotope_groups[isotope_groups['peptide_group'].isnull()]

,raw_indices,frame_indices,scan_indices,precursor_indices,push_indices,tof_indices,rt_values,rt_values_min,mobility_values,quad_low_mz_values,quad_high_mz_values,mz_values,intensity_values,corrected_intensity_values,rt_group,mobility_group,mz_group,peptide_group
0,98648221,2566,786,0,2382034,126326,272.495279,4.541588,0.757508,-1.0,-1.0,400.001315,64,64,272.30466,0.751114,NaN,NaN
1,2612288,172,665,0,160281,126326,18.635681,0.310595,0.892809,-1.0,-1.0,400.001315,164,164,18.50466,0.891114,NaN,NaN
2,40079098,1576,753,0,1463281,126326,167.514939,2.791916,0.794396,-1.0,-1.0,400.001315,28,28,167.30466,0.791114,NaN,NaN
3,55143363,1810,784,0,1680464,126326,192.326686,3.205445,0.759743,-1.0,-1.0,400.001315,70,70,192.20466,0.751114,NaN,NaN
4,5470583,739,698,0,686490,126326,78.754222,1.312570,0.855896,-1.0,-1.0,400.001315,102,102,78.50466,0.851114,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2539410,722218,1,823,0,1751,134101,0.504660,0.008411,0.716159,-1.0,-1.0,424.998579,97,97,NaN,0.711114,424.981315,NaN
2539428,427704,1,642,0,1570,134101,0.504660,0.008411,0.918541,-1.0,-1.0,424.998579,57,57,NaN,0.911114,424.981315,NaN
2539435,538497,1,700,0,1628,134101,0.504660,0.008411,0.853660,-1.0,-1.0,424.998579,44,44,NaN,0.851114,424.981315,NaN
2539438,714904,1,813,0,1741,134101,0.504660,0.008411,0.727333,-1.0,-1.0,424.998579,93,93,NaN,0.721114,424.981315,NaN
2539445,623233,1,746,0,1674,134101,0.504660,0.008411,0.802222,-1.0,-1.0,424.998579,25,25,NaN,0.801114,424.981315,NaN

In [15]:
grouped_window_1_precursors =  group_similar_rows(
    window_1_precursor, 
    rt_tolerance= 60, 
    mobility_tolerance=0.06, 
    mz_tolerance= 0.1
    ).sort_values(by="intensity_values",ascending= False)


# this contains the peptide detector events in the selected quadropole window
# grouped_window_1_precursors.sort_values(by="mobility_values",ascending= False)
grouped_window_1_precursors.sort_values(by="mz_values")

        rt_values  mobility_values   mz_values  intensity_values
11780  291.581747         0.659184  400.018731               342
18151  333.568242         1.388091  400.020314                10
1856    16.725823         1.123438  400.020314                10
4334    61.579239         1.129040  400.020314                67
2205    37.718847         1.427380  400.026647                95
...           ...              ...         ...               ...
4333   101.341621         1.051749  424.975733               367
4719   102.612299         1.157054  424.978997                31
11208  207.595348         1.241689  424.982261               141
10796  223.339735         1.121197  424.987156               228
14650  245.765961         1.298326  424.995316                40

[18799 rows x 4 columns]

In [16]:
# These selected_precursor_mobility and selected_precursor_rt_value are needed
# to find the fragment detector events
quad_low_mz_value = 400.0
selected_precursor_mobility = 0.760861
mobility_threshold = 0.001


selected_precursor_rt_value = 115.976836
rt_value_threshold = 1


precurser_index_1_fragments= data[
    selected_precursor_rt_value - rt_value_threshold: selected_precursor_rt_value + rt_value_threshold,
    selected_precursor_mobility - mobility_threshold: selected_precursor_mobility + mobility_threshold,
    1,
    :]

window_1_fragments = precurser_index_1_fragments[precurser_index_1_fragments["quad_low_mz_values"]== quad_low_mz_value]
# window_1_fragments.sort_values(by="intensity_values",ascending= False)
window_1_fragments

,raw_indices,frame_indices,scan_indices,precursor_indices,push_indices,tof_indices,rt_values,rt_values_min,mobility_values,quad_low_mz_values,quad_high_mz_values,mz_values,intensity_values,corrected_intensity_values
0,13491887,1082,783,1,1004879,56361,115.127354,1.918789,0.760861,400.0,425.0,209.138559,137,137
1,13491888,1082,783,1,1004879,56416,115.127354,1.918789,0.760861,400.0,425.0,209.264506,12,12
2,13491889,1082,783,1,1004879,58963,115.127354,1.918789,0.760861,400.0,425.0,215.138490,297,297
3,13491890,1082,783,1,1004879,64048,115.127354,1.918789,0.760861,400.0,425.0,227.108869,128,128
4,13491891,1082,783,1,1004879,70266,115.127354,1.918789,0.760861,400.0,425.0,242.186765,77,77
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
573,13852971,1091,783,1,1013231,226356,116.081472,1.934691,0.760861,400.0,425.0,779.430151,32,32
574,13852972,1091,783,1,1013231,231083,116.081472,1.934691,0.760861,400.0,425.0,800.463238,181,181
575,13852973,1091,783,1,1013231,235290,116.081472,1.934691,0.760861,400.0,425.0,819.418068,83,83
576,13852974,1091,783,1,1013231,246363,116.081472,1.934691,0.760861,400.0,425.0,870.368176,86,86
577,13852975,1091,783,1,1013231,258818,116.081472,1.934691,0.760861,400.0,425.0,929.513519,172,172

In [17]:
window_1_fragments[["mz_values","intensity_values"]].sort_values(by="mz_values")

       mz_values  intensity_values
310   191.069635                98
311   195.071175               157
0     209.138559               137
1     209.264506                12
2     215.138490               297
..           ...               ...
308   812.449279               112
575   819.418068                83
576   870.368176                86
577   929.513519               172
309  1008.441483               118

[578 rows x 2 columns]

In [18]:
amino_acid_masses_acid_to_weight = {
    'Ala': 71,  # Alanine
    'Arg': 156,  # Arginine
    'Asn': 114,  # Asparagine
    'Asp': 115,  # Aspartic acid
    'Cys': 103,  # Cysteine
    'Gln': 128,  # Glutamine
    'Glu': 129,  # Glutamic acid
    'Gly': 57,   # Glycine
    'His': 137,  # Histidine
    'Ile': 113,  # Isoleucine
    'Leu': 113,  # Leucine
    'Lys': 128,  # Lysine
    'Met': 131,  # Methionine
    'Phe': 147,  # Phenylalanine
    'Pro': 97,   # Proline
    'Ser': 87,   # Serine
    'Thr': 101,  # Threonine
    'Trp': 186,  # Tryptophan
    'Tyr': 163,  # Tyrosine
    'Val': 99    # Valine
}


amino_acid_masses_weigth_to_acid = {
    57: 'Gly',   # Glycine
    71: 'Ala',   # Alanine
    87: 'Ser',   # Serine
    97: 'Pro',   # Proline
    99: 'Val',   # Valine
    101: 'Thr',  # Threonine
    103: 'Cys',  # Cysteine
    113: ['Leu','Ile'],  # Leucine, Isoleucine
    114: 'Asn',  # Asparagine
    115: 'Asp',  # Aspartic acid
    128: 'Lys',  # Lysine
    128: 'Gln',  # Glutamine
    129: 'Glu',  # Glutamic acid
    131: 'Met',  # Methionine
    137: 'His',  # Histidine
    147: 'Phe',  # Phenylalanine
    156: 'Arg',  # Arginine
    163: 'Tyr',  # Tyrosine
    186: 'Trp',  # Tryptophan
}

In [19]:
# finding the precursor mass
precursor_mz = 413.053060
precursor_charge = 2
precursor_mass = precursor_mz * precursor_charge - precursor_charge

In [21]:
def check_key_within_threshold(my_dict, key, threshold):
    for k in my_dict:
        if abs(k - key) <= threshold:
            return True
    
    return False


def get_values_within_threshold(my_dict, key, threshold):
    values_within_threshold = []
    
    # Iterate through all keys in the dictionary
    for k in my_dict:
        # Check if the absolute difference between key k and the given key is within the threshold
        if abs(k - key) <= threshold:
            # If within the threshold, append the corresponding value to the result list
            values_within_threshold.append(my_dict[k])
    
    return values_within_threshold

In [ ]:
# here we get the fragments whose mass is less than the precursor mass
# fragment charge is considered as 1.
# So mz values is equals to its mass

fragement_temp = window_1_fragments[["mz_values","intensity_values"]][window_1_fragments["mz_values"]<precursor_mass].sort_values(by="mz_values",ascending=False)

valid_fragment_indices ={
    # key = raw index, 
    # value  = 
}

for index, row in fragement_temp.iterrows():
    mass = row["mz_values"]
    intensity = row["intensity_values"]
    # print(f"Mass: {mass}, Intensity: {intensity}")
    
    
    y_ion_mass = mass
    b_ion_mass = precursor_mass - y_ion_mass
    mass_threshold = 1
    
    print(f"y_ion_mass: {y_ion_mass}, b_ion_mass: {b_ion_mass}")
    
    # if( b_ion_mass in amino_acid_masses_weigth_to_acid ): #need to add the threshold
    if( check_key_within_threshold(amino_acid_masses_weigth_to_acid, b_ion_mass, mass_threshold)): #need to add the threshold
        print(b_ion_mass, ' is in ')
        break
           

fragement_temp

y_ion_mass: 819.418067559946, b_ion_mass: 4.68805244005398
y_ion_mass: 812.4492788863289, b_ion_mass: 11.656841113671135
y_ion_mass: 800.4632381441517, b_ion_mass: 23.642881855848373
y_ion_mass: 791.3606877865024, b_ion_mass: 32.74543221349768
y_ion_mass: 788.4017862738398, b_ion_mass: 35.70433372616026
y_ion_mass: 781.4380965663366, b_ion_mass: 42.66802343366339
y_ion_mass: 779.4301505864703, b_ion_mass: 44.67596941352974
y_ion_mass: 760.3918148083048, b_ion_mass: 63.71430519169519
y_ion_mass: 759.3793261678526, b_ion_mass: 64.72679383214745
y_ion_mass: 755.3970334664481, b_ion_mass: 68.70908653355195
y_ion_mass: 751.9677846147264, b_ion_mass: 72.13833538527365
y_ion_mass: 749.3998842700523, b_ion_mass: 74.70623572994771
y_ion_mass: 749.2915391873315, b_ion_mass: 74.81458081266851
y_ion_mass: 748.4553787891796, b_ion_mass: 75.65074121082046
y_ion_mass: 746.447038095736, b_ion_mass: 77.65908190426399
y_ion_mass: 746.447038095736, b_ion_mass: 77.65908190426399
y_ion_mass: 745.4438795506724, b_ion_mass: 78.66224044932767
y_ion_mass: 745.4395570514305, b_ion_mass: 78.66656294856955
y_ion_mass: 736.415732623948, b_ion_mass: 87.69038737605206
87.69038737605206  is in

      mz_values  intensity_values
575  819.418068                83
308  812.449279               112
574  800.463238               181
307  791.360688                67
306  788.401786               212
..          ...               ...
2    215.138490               297
1    209.264506                12
0    209.138559               137
311  195.071175               157
310  191.069635                98

[575 rows x 2 columns]

In [23]:
import numpy as np
import pandas as pd

quad_mz_min_value = 200
quad_mz_max_value = 1200


def quantize_mz_and_sum_intensity(df, mz_min, mz_max, bin_width):
    # Define m/z bin edges
    bins = np.arange(mz_min, mz_max + bin_width, bin_width)
    # print((bins))


    df["mz_bin"] = pd.cut(df["mz_values"], bins, right=False, labels=bins[:-1])
    # print(df.groupby("mz_bin", observed=True))

    # Compute weighted sum of intensities for each bin
    grouped_df = df.groupby("mz_bin")["intensity_values"].sum().reset_index()

    return grouped_df

bin_width = 5 # Define bin width

result_df = quantize_mz_and_sum_intensity(window_1_fragments, quad_mz_min_value, quad_mz_max_value, bin_width)
print(result_df)

    mz_bin  intensity_values
0      200                 0
1      205               149
2      210                 0
3      215               430
4      220               148
..     ...               ...
195   1175                 0
196   1180                 0
197   1185                 0
198   1190                 0
199   1195                 0

[200 rows x 2 columns]

C:\Users\havin\AppData\Local\Temp\ipykernel_23856\3316685338.py:18: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grouped_df = df.groupby("mz_bin")["intensity_values"].sum().reset_index()

grouping MS1 detector events by similar rows

In [62]:
# import pandas as pd
# import numpy as np

# # Load data (assuming you already have a DataFrame named df)
# # Define similarity thresholds
# rt_tolerance = 1e-3  # Adjust based on precision needed
# mobility_tolerance = 1e-3
# mz_tolerance = 1e-2

# # Sort values to ensure similar ones are adjacent
# df = window_1_precursor.sort_values(by=["rt_values"])

# # Group similar rows
# def group_similar_rows(df):
#     grouped_data = []
#     current_group = [df.iloc[0]]

#     for i in range(1, len(df)):
#         prev = current_group[-1]
#         curr = df.iloc[i]

#         if (
#             abs(prev["rt_values"] - curr["rt_values"]) < rt_tolerance and
#             abs(prev["mobility_values"] - curr["mobility_values"]) < mobility_tolerance and
#             abs(prev["mz_values"] - curr["mz_values"]) < mz_tolerance
#         ):
#             current_group.append(curr)
#         else:
#             # Aggregate and save the group
#             merged_row = merge_rows(current_group)
#             grouped_data.append(merged_row)
#             current_group = [curr]

#     # Process last group
#     if current_group:
#         grouped_data.append(merge_rows(current_group))

#     return pd.DataFrame(grouped_data)

# # Function to merge a group of similar rows
# def merge_rows(group):
#     merged = group[0].copy()
#     merged["intensity_values"] = sum(row["intensity_values"] for row in group)
#     merged["corrected_intensity_values"] = sum(row["corrected_intensity_values"] for row in group)
#     return merged

# # Apply grouping
# filtered_df = group_similar_rows(df)

# # Display the final dataset
# print(filtered_df)

In [ ]:
# import numpy as np

# frame_indices = alphatims.bruker.convert_slice_key_to_int_array(data, slice(0,10000), "frame_indices")
# scan_indices = alphatims.bruker.convert_slice_key_to_int_array(data, slice(0,500000), "scan_indices")
# precursor_indices = np.array([[0, 1, 1]])
# tof_indices = alphatims.bruker.convert_slice_key_to_int_array(data, slice(0,500000), "tof_indices")
# quad_values = np.array([[-1, 0]])
# intensity_slices = np.arange(0, 1000)


# intensity_values = alphatims.bruker.convert_slice_key_to_float_array(
#                         slice(0,1000)
#                     )

            
# elected_indices = alphatims.bruker.filter_indices(
#                         frame_slices=frame_indices,
#                         scan_slices=scan_indices,
#                         precursor_slices= precursor_indices,
#                         tof_slices=tof_indices,
#                         quad_slices=quad_values,
#                         intensity_slices=intensity_values,
#                         frame_max_index=data.frame_max_index,
#                         scan_max_index=data.scan_max_index,
#                         push_indptr=data.push_indptr,
#                         precursor_indices=data.precursor_indices,
#                         quad_mz_values=data.quad_mz_values,
#                         quad_indptr=data.quad_indptr,
#                         tof_indices=data.tof_indices,
#                         intensities=data.intensity_values
#                     )

# elected_events = data.as_dataframe(
#     elected_indices
# )
# elected_events

array([        0,         1,         2, ..., 126975384, 126975385,
       126975386])

Using np grouping

In [ ]:
import pandas as pd

data_range = 77042361 
chunk_size = 7704236  # Number of rows per chunk




# Iterate through the DataFrame in chunks
for i in range(0, data_range, chunk_size):  # Use 'data_range' instead of 'range'
    chunk = precursor_temp.iloc[i:i + chunk_size]
    temp_df = chunk.groupby(
        ["frame_indices", "scan_indices","precursor_indices","quad_low_mz_values"]
        ).agg({
        "raw_indices": list,
        "push_indices": "first",
        "tof_indices": "first",
        "rt_values": "first",
        "rt_values_min": "first",
        "mobility_values": list,
        "quad_high_mz_values": "first",
        "mz_values": "first",
        "intensity_values": "sum"
    }).reset_index()
    print(temp_df)

In [ ]:

    
final_df = precursor_temp.head(100).groupby(
    ["frame_indices", "scan_indices","precursor_indices","quad_low_mz_values"]
    ).agg({
    "raw_indices": list,
    "push_indices": "first",
    "tof_indices": "first",
    "rt_values": "first",
    "rt_values_min": "first",
    "mobility_values": "first",
    "quad_high_mz_values": "first",
    "mz_values": "first",
    "intensity_values": "sum"
}).reset_index()

# final_df
# Merge back with the original DataFrame to keep all columns (other fields)
final_df = pd.merge(precursor_temp, final_df, on=["frame_indices", "scan_indices","precursor_indices","quad_low_mz_values"], how='left')

In [ ]:
total = 0
for i in range(len(final_df["raw_indices"])):
    total += len(final_df['raw_indices'][i])
    
total

In [ ]:
precursor_temp["intensity_values"]

0            10
1            74
2            35
3           101
4            55
           ...
77042357    124
77042358    132
77042359     58
77042360     89
77042361    106
Name: intensity_values, Length: 77042362, dtype: uint16

In [19]:
precursor_temp.head()

,raw_indices,frame_indices,scan_indices,precursor_indices,push_indices,tof_indices,rt_values,rt_values_min,mobility_values,quad_low_mz_values,quad_high_mz_values,mz_values,intensity_values,corrected_intensity_values
0,0,1,44,0,972,92735,0.50466,0.008411,1.589135,-1.0,-1.0,300.710089,10,10
1,1,1,45,0,973,281963,0.50466,0.008411,1.588011,-1.0,-1.0,1044.585829,74,74
2,2,1,46,0,974,265013,0.50466,0.008411,1.586887,-1.0,-1.0,959.655833,35,35
3,3,1,47,0,975,239005,0.50466,0.008411,1.585764,-1.0,-1.0,836.340583,101,101
4,4,1,49,0,977,291253,0.50466,0.008411,1.583516,-1.0,-1.0,1092.662003,55,55

In [16]:
precursor_temp['frame_indices'].unique()

array([   1,    4,    5, ..., 3174, 3175, 3176])

In [ ]:

# List to store new rows
new_rows = []

# Process each group
for _, group in grouped:
    # Check if mz_values are within the threshold
    mz_values = group['mz_values'].values
    intensity_values = group['intensity_values'].values

    # If mz_values are within the threshold, combine them
    if np.ptp(mz_values) <= mz_threshold:  # ptp is peak-to-peak (max - min)
        # Linear interpolation to get a representative m/z value (e.g., the average)
        interpolated_mz = np.mean(mz_values)
        
        # Sum the intensities
        total_intensity = np.sum(intensity_values)
        
        # Create a new row with combined information
        new_row = {
            'frame_indices': group['frame_indices'].iloc[0],
            'scan_indices': group['scan_indices'].iloc[0],
            'precursor_indices': group['precursor_indices'].iloc[0],
            'quad_low_mz_values': group['quad_low_mz_values'].iloc[0],
            'mz_values': interpolated_mz,  # representative m/z value
            'intensity_values': total_intensity  # summed intensity
        }
        
        # Append the new row to the list
        new_rows.append(new_row)

# Create a DataFrame from the new rows
final_df = pd.DataFrame(new_rows)

print(final_df)

In [28]:
def inspect_peptide(
    dia_data,
    peptide,
    ppm=50,
    rt_tolerance=30, #seconds
    mobility_tolerance=0.05, #1/k0
    heatmap=False
):
    precursor_mz = peptide["mz"]
    precursor_mobility = peptide["mobility"]
    precursor_rt = peptide["rt"]
    fragment_mzs = peptide["fragment_mzs"]
    rt_slice = slice(
        precursor_rt - rt_tolerance,
        precursor_rt + rt_tolerance
    )
    im_slice = slice(
        precursor_mobility - mobility_tolerance,
        precursor_mobility + mobility_tolerance
    )
    precursor_mz_slice = slice(
        precursor_mz / (1 + ppm / 10**6),
        precursor_mz * (1 + ppm / 10**6)
    )
    precursor_indices = dia_data[
        rt_slice,
        im_slice,
        0, #index 0 means that the quadrupole is not used
        precursor_mz_slice,
        "raw"
    ]
    if heatmap:
        precursor_heatmap = alphatims.plotting.heatmap(
            dia_data.as_dataframe(precursor_indices),
            x_axis_label="rt",
            y_axis_label="mobility",
            title="precursor",
            width=250,
            height=250
        )
        overlay = precursor_heatmap
    else:
        precursor_xic = alphatims.plotting.line_plot(
            dia_data,
            precursor_indices,
            x_axis_label="rt",
            width=900,
            remove_zeros=True,
            label="precursor"
        )
        overlay = precursor_xic
    for fragment_name, mz in fragment_mzs.items():
        fragment_mz_slice = slice(
            mz / (1 + ppm / 10**6),
            mz * (1 + ppm / 10**6)
        )
        fragment_indices = dia_data[
            rt_slice,
            im_slice,
            precursor_mz_slice,
            fragment_mz_slice,
            "raw"
        ]
        if len(fragment_indices) > 0:
            if heatmap:
                fragment_heatmap = alphatims.plotting.heatmap(
                    dia_data.as_dataframe(fragment_indices),
                    x_axis_label="rt",
                    y_axis_label="mobility",
                    title=f"{fragment_name}: {mz:.3f}",
                    width=250,
                    height=250,
                )
                overlay += fragment_heatmap
            else:
                fragment_xic = alphatims.plotting.line_plot(
                    dia_data,
                    fragment_indices,
                    x_axis_label="rt",
                    width=900,
                    remove_zeros=True,
                    label=fragment_name,
                )
                overlay *= fragment_xic.opts(muted=True)
    if not heatmap:
        overlay.opts(hv.opts.Overlay(legend_position='bottom'))
        overlay.opts(hv.opts.Overlay(click_policy='mute'))
        overlay = overlay.opts(show_legend=True)
        hv.save(overlay, "tutorial_dia_xic_overlay.html")
    return overlay.opts(
        title=f"{peptide['sequence']}_{peptide['charge']}"
    )